version: '3'

services:

  neo4j:
    build: ./Backend/neo4j
    ports:
      - 7474:7474 # Browser
      - 7687:7687 # Bolt
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes: 
      - $HOME/neo4j/data:/data neo4j

  api:
    build: ./Backend/api
    ports:
      - 4000:4000
    links:
    - neo4j
    depends_on:
    - neo4j

  ui:
    build: ./Frontend
    ports:
      - 5000:5000
    links:
    - api
    depends_on:
    - api
